website/website/app.py
from flask import Flask

from .blueprints.page.views import page
from .blueprints.bible.views import bible

def create_app():
    app = Flask(__name__)
    
    app.register_blueprint(page)
    app.register_blueprint(bible)

    return app

website/website/blueprints/bible/controller.py
import requests

def get_books():
    return requests.get('http://kjv:5000/api/v1/books').json()

def book_lut():
    return dict(get_books()['books'])

def get_api_response(result):
    try:
        data = result.json()
        return data.get('success', False), data
    except ValueError:
        return False, {'bad-json': result.content.decode()}

def get_book(book_id):
    return get_api_response(
        requests.get(
            f'http://kjv:5000/api/v1/book/{book_id}'
        )
    )

def get_chapter(book_id, chapter_number):
    return get_api_response(
        requests.get(
            f'http://kjv:5000/api/v1/chapter/{book_id}/{chapter_number}'
        )
    )

def get_verse(book_id, chapter_number, verse_number):
    return get_api_response(
        requests.get(
            f'http://kjv:5000/api/v1/verse/'
            f'{book_id}/{chapter_number}/{verse_number}'
        )
    )

website/website/blueprints/bible/views.py
from flask import (
    render_template, request, redirect, Blueprint, current_app, url_for,
)

from . import controller

bible = Blueprint('bible', __name__, template_folder='templates')

@bible.route('/search', methods=['post'])
def search():
    current_app.logger.info(request.form['search'])
    return redirect(url_for('page.index'))

@bible.route('/book/<book_id>')
def book_page(book_id):
    success, result = controller.get_book(book_id)
    if success:
        return render_template(
            'bible/book.html.j2',
            verses=result['verses'],
        )
    elif 'reason' in result:
        return result['reason'], 400
    return result['bad-json'], 500

@bible.route('/chapter/<book_id>/<chapter_number>')
def chapter_page(book_id, chapter_number):
    success, result = controller.get_chapter(book_id, chapter_number)
    if success:
        return render_template(
            'bible/chapter.html.j2',
            verses=result['verses'],
        )
    elif 'reason' in result:
        return result['reason'], 400
    return result['bad-json'], 500

@bible.route('/verse/<book_id>/<chapter_number>/<verse_number>')
def verse_page(book_id, chapter_number, verse_number):
    success, result = controller.get_verse(
        book_id, chapter_number, verse_number,
    )
    if success:
        return render_template(
            'bible/verse.html.j2',
            verse=result['verse'],
        )
    elif 'reason' in result:
        return result['reason'], 400
    return result['bad-json'], 500

website/website/blueprints/page/__init__.py
from .views import page

website/website/blueprints/page/views.py
from flask import Blueprint, render_template

page = Blueprint('page', __name__, template_folder='templates')

@page.route('/')
def index():
    return render_template('page/index.html')

@page.route('/terms')
def terms():
    return render_template('page/terms.html')

@page.route('/privacy')
def privacy():
    return render_template('page/privacy.html')

@page.route('/faq')
def faq():
    return render_template('page/faq.html')

website/website/templates/layouts/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}" />

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="{{ url_for("page.index") }}">Biblr</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for("page.privacy") }}">Privacy</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for("page.terms") }}">ToS</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for("page.faq") }}">FAQ</a>
          </li>
        </ul>
        <form class="form-inline mt-2 mt-md-0" action="{{ url_for("bible.search") }}" method="POST">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <main role="main" class="container">
      {% block preheader %}{% endblock %}
      <h1>{% block heading %}{% endblock %}</h1>
      {% block body %}{% endblock %}
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>