website/website/blueprints/bible/controller.py
import requests

def get_books():
    return requests.get('http://kjv:5000/api/v1/books').json()

def book_lut():
    return dict(get_books()['books'])

def get_api_response(result):
    try:
        data = result.json()
        return data.get('success', False), data
    except ValueError:
        return False, {'bad-json': result.content.decode()}

def get_book(book_id):
    return get_api_response(
        requests.get(
            f'http://kjv:5000/api/v1/book/{book_id}'
        )
    )

def get_chapter(book_id, chapter_number):
    return get_api_response(
        requests.get(
            f'http://kjv:5000/api/v1/chapter/{book_id}/{chapter_number}'
        )
    )

def get_verse(book_id, chapter_number, verse_number):
    return get_api_response(
        requests.get(
            f'http://kjv:5000/api/v1/verse/'
            f'{book_id}/{chapter_number}/{verse_number}'
        )
    )

website/website/blueprints/bible/views.py
from flask import (
    render_template, request, redirect, Blueprint, current_app, url_for,
)

from . import controller

bible = Blueprint('bible', __name__, template_folder='templates')

@bible.route('/search', methods=['post'])
def search():
    current_app.logger.info(request.form['search'])
    return redirect(url_for('page.index'))

@bible.route('/book/<book_id>')
def book_page(book_id):
    success, result = controller.get_book(book_id)
    if success:
        return render_template(
            'bible/book.html.j2',
            verses=result['verses'],
        )
    elif 'reason' in result:
        return result['reason'], 400
    return result['bad-json'], 500

@bible.route('/chapter/<book_id>/<chapter_number>')
def chapter_page(book_id, chapter_number):
    success, result = controller.get_chapter(book_id, chapter_number)
    if success:
        return render_template(
            'bible/chapter.html.j2',
            verses=result['verses'],
        )
    elif 'reason' in result:
        return result['reason'], 400
    return result['bad-json'], 500

@bible.route('/verse/<book_id>/<chapter_number>/<verse_number>')
def verse_page(book_id, chapter_number, verse_number):
    success, result = controller.get_verse(
        book_id, chapter_number, verse_number,
    )
    if success:
        return render_template(
            'bible/verse.html.j2',
            verse=result['verse'],
        )
    elif 'reason' in result:
        return result['reason'], 400
    return result['bad-json'], 500

website/website/blueprints/bible/templates/bible/book.html.j2
{% extends 'layouts/base.html' %}

{% block title %}Biblr{% endblock %}

{% block body %}
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Book</th>
        <th scope="col">Chapter</th>
        <th scope="col">Verse</th>
        <th scope="col">Text</th>
      </tr>
    </thead>
    <tbody>
      {% for v in verses: %}
        <tr>
          <td><a class="btn btn-light" href="{{ url_for("bible.book_page", book_id=v.b) }}">{{ v.b }}</a></td>
          <td><a class="btn btn-light" href="{{ url_for("bible.chapter_page", book_id=v.b, chapter_number=v.c) }}">{{ v.c }}</a></td>
          <td><a class="btn btn-light" href="{{ url_for("bible.verse_page", book_id=v.b, chapter_number=v.c, verse_number=v.v) }}">{{ v.v }}</a></td>
          <td>{{ v.text }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

website/website/blueprints/bible/templates/bible/chapter.html.j2
{% extends 'layouts/base.html' %}

{% block title %}Biblr{% endblock %}

{% block body %}
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Book</th>
        <th scope="col">Chapter</th>
        <th scope="col">Verse</th>
        <th scope="col">Text</th>
      </tr>
    </thead>
    <tbody>
      {% for v in verses: %}
        <tr>
          <td><a class="btn btn-light" href="{{ url_for("bible.book_page", book_id=v.b) }}">{{ v.b }}</a></td>
          <td><a class="btn btn-light" href="{{ url_for("bible.chapter_page", book_id=v.b, chapter_number=v.c) }}">{{ v.c }}</a></td>
          <td><a class="btn btn-light" href="{{ url_for("bible.verse_page", book_id=v.b, chapter_number=v.c, verse_number=v.v) }}">{{ v.v }}</a></td>
          <td>{{ v.text }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

website/website/blueprints/bible/templates/bible/verse.html.j2
{% extends 'layouts/base.html' %}

{% block title %}Biblr{% endblock %}

{% block body %}
  <table class="table">
    <thead>
    </thead>
    <tbody>
      <tr>
        <th scope="row">Book</th>
        <td><a class="btn btn-light" href="{{ url_for("bible.book_page", book_id=verse.b) }}">{{ verse.b }}</a></td>
      </tr>
      <tr>
        <th scope="row">Chapter</th>
        <td><a class="btn btn-light" href="{{ url_for("bible.chapter_page", book_id=verse.b, chapter_number=verse.c) }}">{{ verse.c }}</a></td>
      </tr>
      <tr>
        <th scope="col">Verse</th>
        <td>{{ verse.v }}</td>
      </tr>
      <tr>
        <th scope="col">Text</th>
        <td>{{ verse.text }}</td>
      </tr>
    </tbody>
  </table>
{% endblock %}